// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk-78CyzC6vPH80nk2BcTbLYtIJ-m6n-c',
    appId: '1:1065502353738:web:4b62fe0222f4613f2d79b3',
    messagingSenderId: '1065502353738',
    projectId: 'blog-cpmad-app',
    authDomain: 'blog-cpmad-app.firebaseapp.com',
    storageBucket: 'blog-cpmad-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaA-0oC4hjChhfdv_dBFX2-Vg67k5lMlg',
    appId: '1:1065502353738:android:2de4e3c080107cd12d79b3',
    messagingSenderId: '1065502353738',
    projectId: 'blog-cpmad-app',
    storageBucket: 'blog-cpmad-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbMiueWzPY_tKYSyvBgds_i5hh2jb83gk',
    appId: '1:1065502353738:ios:b78128b9856dc46d2d79b3',
    messagingSenderId: '1065502353738',
    projectId: 'blog-cpmad-app',
    storageBucket: 'blog-cpmad-app.firebasestorage.app',
    iosBundleId: 'com.example.blogApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbMiueWzPY_tKYSyvBgds_i5hh2jb83gk',
    appId: '1:1065502353738:ios:b78128b9856dc46d2d79b3',
    messagingSenderId: '1065502353738',
    projectId: 'blog-cpmad-app',
    storageBucket: 'blog-cpmad-app.firebasestorage.app',
    iosBundleId: 'com.example.blogApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk-78CyzC6vPH80nk2BcTbLYtIJ-m6n-c',
    appId: '1:1065502353738:web:49343a27f40d10782d79b3',
    messagingSenderId: '1065502353738',
    projectId: 'blog-cpmad-app',
    authDomain: 'blog-cpmad-app.firebaseapp.com',
    storageBucket: 'blog-cpmad-app.firebasestorage.app',
  );

}