// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKmhHh8hQXvLEuI3xfPwpdJd7p8jwIgzQ',
    appId: '1:747554933486:web:ed10663a3fbaf3f0f2c1ff',
    messagingSenderId: '747554933486',
    projectId: 'expense-tracker-cpmad',
    authDomain: 'expense-tracker-cpmad.firebaseapp.com',
    storageBucket: 'expense-tracker-cpmad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtbkTvcLGqsG8sQwISx1Gjr9l15I65kxM',
    appId: '1:747554933486:android:57de5654f959154ff2c1ff',
    messagingSenderId: '747554933486',
    projectId: 'expense-tracker-cpmad',
    storageBucket: 'expense-tracker-cpmad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjzCNZupcHOgu1nFEJbKi42HIYx11ZdXA',
    appId: '1:747554933486:ios:7db439de1e61b757f2c1ff',
    messagingSenderId: '747554933486',
    projectId: 'expense-tracker-cpmad',
    storageBucket: 'expense-tracker-cpmad.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjzCNZupcHOgu1nFEJbKi42HIYx11ZdXA',
    appId: '1:747554933486:ios:7db439de1e61b757f2c1ff',
    messagingSenderId: '747554933486',
    projectId: 'expense-tracker-cpmad',
    storageBucket: 'expense-tracker-cpmad.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKmhHh8hQXvLEuI3xfPwpdJd7p8jwIgzQ',
    appId: '1:747554933486:web:a600caf874d8e625f2c1ff',
    messagingSenderId: '747554933486',
    projectId: 'expense-tracker-cpmad',
    authDomain: 'expense-tracker-cpmad.firebaseapp.com',
    storageBucket: 'expense-tracker-cpmad.firebasestorage.app',
  );
}
